### PR TITLE
[UPGRADE] Umbraco & uSync

### PR DESCRIPTION
**Pull request by OwainWilliams**
- Upgrade Umbraco to 10.2.1
- Upgrade uSync to 10.2.1
- Full Export of uSync files so they are up to date with the new uSync version
- #7

### CODE REVIEW

**Comment by prjseal** [comment]
Hi mate, the upgrade of Umbraco would be just 2 csproj files. Your PR had 67 file changes. I had to investigate this to make sure and in the process of investigating I did the upgrade. Sorry but I'm going to close this PR. I'm sure there are other PRs you could help with.

**Comment by NikRimington** [comment]
@prjseal after upgrading Umbraco you should always regen the models builder models. This results in the models files changing because models build puts a hash into the comments in those files. So it should be more than 2 files as all the models builder files should update.

**Comment by prjseal** [comment]
Good point. I'll build the models again and commit them. Sorry @OwainWilliams we've got loads of other issues that can easily be done.

**Comment by prjseal** [comment]
I think my main issue was it was combined with a uSync upgrade and some of those files didn't look right. The paths for the quizzes seemed wrong

**Pull request closed without merging**
