### PR TITLE
Refactor from GetMemberModelByUser to GetMemberModelByMember

### PR DESCRIPTION
**Pull request by georgebid**
Decide to use the GetMemberByModelByMember to get the current member mode as it was used the most and  GetMemberModelByUser was using member details so seemed more logical this way. 

Manually tested and everything worked as expected.

### CODE REVIEW

**Comment by prjseal** [comment]
Hi @georgebid thanks for this PR. I do appreciate it, but what is the reasoning behind it?
I could be mistaken, but I think the MemberService uses the database so I think it might be reducing performance by making it hit the database each time. I'm happy to discuss it further though.

**Comment by prjseal** [comment]
Oh now I understand, sorry I forgot I created this issue. #13 
Please can you update your branch with the latest commits in main and I will review it.

Many thanks

**Comment by georgebid** [comment]
Sorry Paul, I should have linked the bug I was working on in my pr! I have updated my branch with the latest commits in main so should be ready for review now :)

**Comment by prjseal** [comment]
Sorry to be a pain, can you merge main back into your branch again please? I've just pushed an update that let's people hide their profile, this way they can take part in the quizzes and learn stuff without having to show everyone their results.

Once you have updated it again and fixed the conflicts I will review your code before working on any more code myself or merging anyone elses.

**Comment by georgebid** [comment]
@prjseal I have resolved the conflicts - is that sufficient?

**Review by prjseal — APPROVED** [review]

**Comment by prjseal** [comment]
All good, thank you, sorry for the back and forth

**Pull request merged**
