### PR TITLE
Delete profile

### PR DESCRIPTION
**Pull request by TECKSPEED**
allow members to delete the profile they use, and log them out upon completion

### CODE REVIEW

**Comment by TECKSPEED** [comment]
Closing Due to rogue folder that I will cleanup

**Comment by prjseal** [comment]
HI @TECKSPEED 
Thanks for this PR, it looks great. 
Before I merge it, please can you delete the uSync config files for the content and media items for your profile images and duplicate quiz page etc, and also delete the media files. I don't want to bring those into the main repo too. Just the code and the doc types etc for the new page. Does that make sense. It makes for a cleaner PR and less in the main repo

**Comment by TECKSPEED** [comment]
@prjseal yeah let me delete those out, I thought I messed up and should of only committed the relevant portions. Apologies

**Comment by prjseal** [comment]
@TECKSPEED also please rebuild the models builder models as they are showing as out of date

**Comment by TECKSPEED** [comment]
@prjseal removed the uSync imagery/content and rebuilt the models on my end. Let me know if you have any more issues or I missed something please

**Review by prjseal — APPROVED** [review]
This looks great, thank you so much 🙏

**Pull request closed without merging**
